### ISSUE TITLE
Yarn 3.2.2 - tslib missing on dependencies from response-cache-redis

### ISSUE THREAD

**Issue by viniciuspalma** [graphql-hive/envelop#1497]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) available on [Stackblitz](https://stackblitz.com/fork/node).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

```sh
13:11:46 - Found 0 errors. Watching for file changes.
/Users/vini/projects/order-bff/.pnp.cjs:24662
      Error.captureStackTrace(firstError);
            ^

Error: @envelop/response-cache-redis tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: tslib
Required by: @envelop/response-cache-redis@npm:1.1.0 (via /Users/vini/projects/order-bff/.yarn/cache/@envelop-response-cache-redis-npm-1.1.0-c8131b30a2-1151c5305d.zip/node_modules/@envelop/response-cache-redis/cjs/)

Require stack:
- /Users/vini/projects/order-bff/.yarn/cache/@envelop-response-cache-redis-npm-1.1.0-c8131b30a2-1151c5305d.zip/node_modules/@envelop/response-cache-redis/cjs/index.js
- /Users/vini/projects/order-bff/.yarn/__virtual__/@hub-tech-graphql-server-virtual-27baa962d5/2/graphql-server/dist/index.js
- /Users/vini/projects/order-bff/packages/server/build/src/index.js
    at Function.require$$0.Module._resolveFilename (/Users/vini/projects/order-bff/.pnp.cjs:24662:13)
    at Module.Hook.Module.require (/Users/vini/projects/order-bff/.yarn/unplugged/dd-trace-npm-3.0.0-9de71772ad/node_modules/dd-trace/packages/dd-trace/src/ritm.js:51:29)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/vini/projects/order-bff/.yarn/cache/@envelop-response-cache-redis-npm-1.1.0-c8131b30a2-1151c5305d.zip/node_modules/@envelop/response-cache-redis/cjs/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Object.require$$0.Module._extensions..js (/Users/vini/projects/order-bff/.pnp.cjs:24706:33)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.require$$0.Module._load (/Users/vini/projects/order-bff/.pnp.cjs:24546:14)
    at Module.require (node:internal/modules/cjs/loader:999:19)

Node.js v17.5.0
```

By installing @envelop/response-cache-redis@1.1.0 on Yarn 3.2.2 with PnP enabled, I get many issues with dependency validation to a library called tslib.

**To Reproduce**
- Create workspace via yarn `yarn init`
- Set version to 3.2.2 `yarn set version 3.2.2`
- Install @envelop/core
- Install @envelop/response-cache
- Install @envelop/response-cache-redis

**Expected behavior**

Dependencies should

**Environment:**

- OS: MacOS
- NodeJS: 17.5.0
- `@envelop/*` versions:
    - "@envelop/core": "2.5.0",
    - "@envelop/response-cache": "3.1.0",
    - "@envelop/response-cache-redis": "1.1.0",
    - 
**Additional context**

**Comment by viniciuspalma** [comment]
Current workaround is to use Package extension to each of the subsequent packages, on `yarnrc.yml`:

```yml
packageExtensions:
  '@envelop/core@2.5.0':
    dependencies:
      tslib: '*'

  '@envelop/types@2.3.1':
    dependencies:
      tslib: '*'

  '@envelop/validation-cache@4.6.0':
    dependencies:
      tslib: '*'

  '@envelop/parser-cache@4.6.0':
    dependencies:
      tslib: '*'

  '@envelop/response-cache@3.1.0':
    dependencies:
      tslib: '*'

  '@envelop/response-cache-redis@1.1.0':
    dependencies:
      tslib: '*'
```
